POST http://localhost:4002/products
Content-Type: application/json

{
  "name": "Mouse Gamer",
  "price": 5000
}

###

GET http://localhost:4002/products

###

GET http://localhost:4002/products/1f7387d2-2bd4-441a-9694-f10ef60c84e2


###
PUT http://localhost:4002/products/d1cc8669-3423-44b9-9174-33722639b6fd
Content-Type: application/json

{
  "name": "Mouse Gamer muito bom",
  "price": 102154
}


###
DELETE  http://localhost:4002/products/e7ee7b4c-ea45-4f9a-982f-e0195714543f