POST http://localhost:4002/products
Content-Type: application/json

{
  "name": "Carro",
  "price": 34343
}

###

GET http://localhost:4002/products

###


###
PUT http://localhost:4002/products/af43cf49-4ce5-4dae-9b27-48cb510c7100
Content-Type: application/json

{
  "name": "Mouse",
  "price": 300
}


###
DELETE  http://localhost:4002/products/f48da998-e01f-4205-bc74-ee5429f68be1